Move pages inside `/nebula` route
DefinedNet/nebula-docs pull request #15
Opened 2021-12-20 14:55 UTC by IanVS

This addresses an issue with internal links between docs pages.  We host these nebula docs at `www.defined.net/nebula`, whereas we were serving them in this repo directly out of the root.  This PR unifies the structure, so that we can use root-relative links between the pages, and they will work here when building/previewing the docs in this repo.  

Also, since we currently are not using localized pages on defined.net, this adds the ability to use urls like `/nebula/overview` directly, and it will work in both defined.net as well as in this repo.

2021-12-20 20:46 UTC, briankelly requested changes
fix config page so that it loads from local server

- `/nebula/en/config` throws a 500
- `/nebula/config` works, but it's not linked in the sidebar (and the other guides include `/en`)

2021-12-20 20:46 UTC, briankelly commented on src/pages/nebula/[slug].astro
> +if (isConfigRefPage) {
I'm not sure what this if block is doing, but I noticed that when running the `nebula-docs` server locally, that I get a 500 when viewing the config page linked from the sidebar (`/nebula/en/config`).

It does load if I attempt to view `/nebula/config`, but all the other pages are okay when `en` is included in the URI.

I tried commenting out this if block and that prevented the 500 from showing, but I'm not sure what the side-effects might be.

2021-12-21 19:35 UTC, IanVS commented on src/pages/nebula/[slug].astro
> +if (isConfigRefPage) {
Thanks for the catch, I pushed up a fix.

2021-12-21 21:45 UTC, IanVS commented
Alrighty, I've pushed a change to handle https://github.com/withastro/astro/issues/1415.  I think this should be ready for a final lookover.

2021-12-21 22:20 UTC, briankelly reviewed
All pages load, but I have a few questions about nav highlights.

2021-12-21 22:20 UTC, briankelly commented on src/components/MobileNav.astro
>  const allPages = Astro.fetchContent('../data/**/*.md');
I noticed that the **Guides** index is not included in the mobile drop-down navigation.

Is this expected?

2021-12-21 22:20 UTC, briankelly commented on src/components/MobileNav.astro
>  const allPages = Astro.fetchContent('../data/**/*.md');
![image](https://user-images.githubusercontent.com/306395/147004607-ec6d6484-8945-41af-821a-b24f3724b8ff.png)

2021-12-21 22:20 UTC, briankelly commented on src/components/LeftSidebar/LeftSidebar.astro
> +const currentPage = Astro.request.canonicalURL.pathname;
When in Desktop view, **Overview**, **Guides**, and **Configuration Reference** get highlighted correctly in the left-sidebar, but _Quick Start_ and _ Extend network access beyond overlay hosts_ do not. 

Is this expected?

Note: Those pages _do_ get highlighted correctly when viewing as part of the www site.

Expected: 
![image](https://user-images.githubusercontent.com/306395/147005037-1161c027-c700-4d47-8e5f-4b8ca834563a.png)

Not highlighted:
![image](https://user-images.githubusercontent.com/306395/147005077-152d1338-cd92-48ab-a420-658d0df4d69d.png)

2021-12-21 22:28 UTC, briankelly approved these changes

2021-12-21 22:29 UTC, briankelly commented on src/components/LeftSidebar/LeftSidebar.astro
> +const currentPage = Astro.request.canonicalURL.pathname;
expected behavior - resolving

2021-12-21 22:29 UTC, briankelly commented on src/components/MobileNav.astro
>  const allPages = Astro.fetchContent('../data/**/*.md');
expected behavior - resolving

2021-12-22 14:31 UTC, merged