Update nebula config reference
DefinedNet/nebula-docs pull request #27
Opened 2022-05-27 15:47 UTC by jasikpark

2022-05-27 19:51 UTC, IanVS commented on src/data/config-reference.md
> +            port is the UDP port nebula should use on a host. setting this to `0`
If the default is `0`, does "setting this to `0`" really make a difference?  Or, should we say that leaving it at the default dynamically....

2022-05-27 19:53 UTC, JohnMaguire commented on src/data/config-reference.md
> +            port is the UDP port nebula should use on a host. setting this to `0`
This is the existing text that I believe comes originally from the `config.yml`. "setting this to `0`" makes sense to me, and makes it clear what happens if you explicitly set it, e.g. through an ansible playbook

```
port: {{ port | default(0) }}
```

2022-05-27 20:29 UTC, IanVS commented on src/data/config-reference.md
> +            port is the UDP port nebula should use on a host. setting this to `0`
I would prefer language like `A value of "0" (the default) will dynamically assign a port number.`

As it is, it makes it sound like the default value is not to dynamically assign a port number, and that setting the value will cause that to happen.  But, I'm 1/5, feel free to ignore.

2022-05-27 21:05 UTC, IanVS commented
You'll need to change the CMS config as well, to expose these settings.

2022-06-02 16:13 UTC, jasikpark commented
> You'll need to change the CMS config as well, to expose these settings.

Mind pairing w/ me on this? I'm not sure how or where I'd pull them in

2022-06-03 18:01 UTC, IanVS requested changes
I think we might want to find a way to explain what `reloadable` means, and we should definitely get a review on the content from @nbrownus.  But I only had one blocker here.

2022-06-03 18:02 UTC, jasikpark commented on src/components/ConfigReference.astro
> +          defaultValue={option.default}
oops, I was copying over from the `www` PR

2022-06-03 18:08 UTC, jasikpark commented
Yeah, I don't fully understand what sending `SIGHUP` would mean exactly... I guess it's as much as:

> While nebula is running for `RELOADABLE` properties you can edit the values in the config and signal the running nebula process with `SIGHUP` to have nebula update those config properties.
> ex:
> run `ps aux | grep nebula` to find nebula's PID & then run `kill -s HUP $PID`

2022-06-03 18:37 UTC, IanVS approved these changes

2022-06-22 13:37 UTC, jasikpark commented
@nbrownus do you think this could be merged if we yoink out the `required` pills for the moment and only add the `default` pills + the updated docs?

2022-06-23 14:53 UTC, nbrownus commented
I will need to re-review the copy but in general yes, I think we need to workshop the reloadable indicators more.

2022-06-23 15:00 UTC, jasikpark commented
> I will need to re-review the copy but in general yes, I think we need to workshop the reloadable indicators more.

Ok, I'll try to push up a commit that removes the "reloadable" indicators before too long

2022-08-22 14:10 UTC, jasikpark commented
Replaced by #42

2022-08-22 14:10 UTC, closed without merging