Add CI
DefinedNet/nebula-docs pull request #89
Opened 2023-01-13 17:55 UTC by jasikpark

2023-01-13 17:57 UTC, jasikpark commented
Not sure why the actions aren't running?

2023-01-13 17:57 UTC, jasikpark commented
Oh, needed to enable "run all actions" rather than just DN authored actions.

2023-01-18 19:34 UTC, IanVS requested changes
I changed the setting to all outside collaborators for now.  If that becomes a burden we can change it back.

2023-01-18 19:34 UTC, IanVS commented on .github/workflows/ci.yaml
> +        uses: volta-cli/action@v4
We can add `cache: npm` here (and in the other jobs) to speed things up slightly.

2023-01-18 19:34 UTC, IanVS commented on .github/workflows/ci.yaml
> +        run: npm install
Let's use `npm ci`

2023-01-18 19:44 UTC, closed without merging